# Generated by Django 5.0.4 on 2024-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.FileField(default='profile.png', upload_to='myimage'),
        ),
    ]
